### ISSUE TITLE
Creating room via REST API first works but then returns empty rooms array

### ISSUE THREAD

**Issue by exitsimulation** [RubyResearch/Agent#4955]
**Describe the bug**

I am creating a room for an existing agent via the Rest API which returns a success response

POST `/api/agents/b850bc30-45f8-0041-a00a-83df46d8555d/rooms` with 
```
{
  "name": "TestRoom",
  "worldId": "00000000-0000-0000-0000-000000000000",
  "roomId": "c06bb360-e84f-49ff-b43a-75a9eb6df8f3",
  "enitityId": "b850bc30-45f8-0041-a00a-83df46d8555d"
}
```

Response:
```
{
    "success": true,
    "data": {
        "id": "143da10d-b1e5-00cb-b315-a64f6062d9de",
        "name": "TestRoom",
        "agentId": "b850bc30-45f8-0041-a00a-83df46d8555d",
        "createdAt": 1749153906448,
        "source": "client",
        "type": "dm",
        "worldId": "00000000-0000-0000-0000-000000000000",
        "serverId": "server-1749153906404"
    }
}
```

Now, the strange thing is then when I call the rooms endpoint via GET
`api/agents/b850bc30-45f8-0041-a00a-83df46d8555d/rooms`

I am getting an empty array

```
{
    "success": true,
    "data": {
        "rooms": []
    }
}
```

Also the ID in the success response is not the one that I supplied in the request.

It seems like internally the room has not been created despite the success response?

Is this a bug in the current version? I am on 1.0.4. Any help would be appreciated!

**Comment by standujar** [comment]
Hello. Should be fixed since v1.0.4. Can you try in v1.0.5 ?

**Comment by exitsimulation** [comment]
Hi @standujar

I just tried 1.0.5 and this is still happening for me. I cannot create any rooms

**Comment by standujar** [comment]
Did you sent a message on this room ? :)

```
{
  "success": true,
  "data": {
    "rooms": [
      {
        "id": "6bb987ad-49f5-0fcd-b4b4-965cd789e392",
        "agentId": "a2c1b813-426d-067e-9d29-93b254e358a8",
        "source": "discord",
        "type": "group",
        "serverId": "1220655979612606504",
        "worldId": "ceffe4fe-7988-0861-9d67-08b444143992",
        "name": "cartman-agent2",
        "metadata": null,
        "channelId": "1349720978653052958",
        "createdAt": 1749202076317,
        "worldName": "KODY"
      }
    ]
  }
}
```

**Comment by exitsimulation** [comment]
I digged a bit into the code and it seems like serverId is trying to be a validated as a Uuid

![Image](https://github.com/user-attachments/assets/9ddb45f0-4eef-410c-9961-fb2ce3c3b02a)

```
    if (!validateUuid(serverId)) {
      sendError(res, 400, 'BAD_REQUEST', 'Missing or invalid global serverId in request body');
      return;
    }
```
in agent.ts

However on room creation I am receiving back a serverId in the format "server-{id}"

```
{
    "success": true,
    "data": {
        "id": "e78080ea-56cb-02dd-b1bb-c273925f5bc9",
        "name": "TestRoom",
        "agentId": "b850bc30-45f8-0041-a00a-83df46d8555d",
        "createdAt": 1749200897353,
        "source": "client",
        "type": "DM",
        "worldId": "00000000-0000-0000-0000-000000000000",
        "serverId": "server-1749200897330"
    }
}
```

I think this might be the issue? serverId should not be treated as a uuid in agent.ts or am I wrong?

In any case, if I input a valid random uuid for serverId (or even the same as room ID) I am getting `Missing or invalid entityId (sender) in request body`. So how do I provide a valid entity ID when sending via API?

**Comment by standujar** [comment]
But this issue should be closed, since the API is responding correctly with real roomsIDs were the agents is registered in (after getting a first message)

**Comment by wtfsayo** [comment]
hey @exitsimulation did you figure it out? from https://github.com/elizaOS/eliza/issues/5121
